language: node_js
node_js: stable

install:
  - npm install

script:
  - gulp build

  - export BRANCH_EXISTS=$(git ls-remote --heads https://${GH_REF} gh-pages)
  - echo $BRANCH_EXISTS

  - if [ -n $BRANCH_EXISTS ]; then
      git init tempdir;
      mv ./dist/* tempdir;
      cd tempdir;
      git checkout -b gh-pages;
    else
      git clone --depth=1 --branch=gh-pages https://${GH_REF} tempdir;
      rm -rf ./tempdir/*;
      mv ./dist/* tempdir;
      cd tempdir;
      git checkout gh-pages;
    fi

  - git add --force .
  - git commit -m "Published from $TRAVIS_BRANCH ($TRAVIS_COMMIT_MESSAGE). Build $TRAVIS_BUILD_NUMBER"
  - git push --force "https://${GithubToken}@${GH_REF}" gh-pages:gh-pages

after_success:
  - curl -l "https://sc.ftqq.com/$serverChan.send?text=Build_success~&desp=Build_$TRAVIS_BUILD_NUMBER"

after_failure:
  - curl -l "https://sc.ftqq.com/$serverChan.send?text=Build_failure~&desp=Build_$TRAVIS_BUILD_NUMBER"

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/ewfian/SimpleSheet.git
